export const tableData = [
  {
    name: 'Apple MacBook Pro 17"',
    color: "Sliver",
    category: "Laptop",
    price: "$2999",
  },
  {
    name: "Microsoft Surface Pro",
    color: "White",
    category: "Laptop",
    price: "$1999",
  },
  {
    name: 'Apple MacBook Air 13"',
    color: "Gold",
    category: "Laptop",
    price: "$1499",
  },
  {
    name: 'Apple iPad Pro 12.9"',
    color: "Sliver",
    category: "Tablet",
    price: "$999",
  },
  {
    name: 'Apple iPad Pro 11"',
    color: "Sliver",
    category: "Tablet",
    price: "$799",
  },
  {
    name: 'Apple iPad Air 10.9"',
    color: "Sliver",
    category: "Tablet",
    price: "$599",
  },
  {
    name: 'Apple iPad 10.2"',
    color: "Sliver",
    category: "Tablet",
    price: "$499",
  },
  {
    name: "Apple iPhone 12 Pro Max",
    color: "Gold",
    category: "Phone",
    price: "$1099",
  },
  {
    name: "Apple iPhone 12 Pro",
    color: "Gold",
    category: "Phone",
    price: "$999",
  },
  {
    name: "Apple iPhone 12",
    color: "Gold",
    category: "Phone",
    price: "$799",
  },
  {
    name: "Apple iPhone 12 mini",
    color: "Gold",
    category: "Phone",
    price: "$699",
  },
  {
    name: "Apple iPhone 11 Pro Max",
    color: "Gold",
    category: "Phone",
    price: "$999",
  },
  {
    name: "Apple iPhone 11 Pro",
    color: "Gold",
    category: "Phone",
    price: "$899",
  },
  {
    name: "Apple iPhone 11",
    color: "Gold",
    category: "Phone",
    price: "$699",
  },
  {
    name: "Apple iPhone SE",
    color: "Gold",
    category: "Phone",
    price: "$399",
  },
  {
    name: "Apple iPhone XR",
    color: "Gold",
    category: "Phone",
    price: "$499",
  },
  {
    name: "Apple iPhone 8",
    color: "Gold",
    category: "Phone",
    price: "$399",
  },
  {
    name: "Apple iPhone 7",
    color: "Gold",
    category: "Phone",
    price: "$299",
  },
  {
    name: "Apple iPhone 6",
    color: "Gold",
    category: "Phone",
    price: "$199",
  },
  {
    name: "Apple iPhone 5",
    color: "Gold",
    category: "Phone",
    price: "$99",
  },
  {
    name: "Apple iPhone 4",
    color: "Gold",
    category: "Phone",
    price: "$49",
  },
  {
    name: "Apple iPhone 3",
    color: "Gold",
    category: "Phone",
    price: "$9",
  },
];
